######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 14 13:06:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . class
INCLUDEPATH += . class

# Input
HEADERS += function.h class/Item.h class/Stud.h class/Student.h
SOURCES += function.cpp main.cpp class/Item.cpp class/Stud.cpp class/Student.cpp
